### ISSUE TITLE
the java version 16.0.2

### ISSUE THREAD

**Issue by iNANOV** [jdemetra/rjdemetra#104]
Hello,

RJDemetra cannot be loaded, because of the new java version 16.0.2.

Can you enable 16.0.2 or is there a strict requirement which blocks you to have higher version of Java?

Details:

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

> library(RJDemetra)
Error: package or namespace load failed for ‘RJDemetra’:
 .onLoad failed in loadNamespace() for 'RJDemetra', details:
  call: fun(libname, pkgname)
  error: You need Java JRE >= 8 and <= 15 to use 'RJDemetra'

**Comment by AQLT** [comment]
Hello,
It is fixed in the last PR (#105). I will soon send it to CRAN.

**Comment by iNANOV** [comment]
Hello,

Thank you for the info.

I tired also the GitHub 2.0 version, but I received again an error message:

> library(RJDemetra)
Error: package or namespace load failed for ‘RJDemetra’ in get(Info[i, 1], envir = env):
 lazy-load database 'C:/Users/Public/R/R4_libs_x86_64/RJDemetra/R/RJDemetra.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by AQLT** [comment]
Maybe try to uninstall `RJDemetra`, to delete the corresponding folder that is in `.libPaths()` and to install it again

**Comment by iNANOV** [comment]
I reinstalled RJDemetra and the corresponding folder was deleted automatically as well. 

I installed again with 

devtools::install_github("jdemetra/rjdemetra", INSTALL_opts = "--no-multiarch")

, but the issue is not solved.

**Comment by AQLT** [comment]
Which R version are you using and which OS? Do you have Rtools installed? Do you have the same problem installing other packages from github? It seems to be a local issue

**Comment by iNANOV** [comment]
For the first question, please see my initial comment. 

I have the library devtools, as I am using it for installing from GitHub.

I did not have  issue with other GitHub packages.

The installation from GitHub finished successfully. 

I can also wait for the CRAN release and try from there.

**Comment by AQLT** [comment]
Very strange.
It's now on CRAN but the windows binaries are not yet available.

**Comment by iNANOV** [comment]
Thank you very much for the support. 

I reinstalled & installed everything once again and the GitHub version is now working!
