### ISSUE TITLE
Bomb with JDemetra 0.2.4

### ISSUE THREAD

**Issue by DonPipo85** [jdemetra/rjdemetra#115]
I use R version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics" and installed RJDemetra 0.2.4.

When runninng library(RJDemetra), I get the bomb in RStudio. Any clues what could be going on?

**Comment by AQLT** [comment]
Is `rJava` working?
```r
library(rJava)
.jinit()
.jcall("java/lang/System", "S", "getProperty", "java.runtime.version")
```

**Comment by DonPipo85** [comment]
You got me, I get the bomb as well. I guess it fails due to security reasons on my corporate laptop

**Comment by AQLT** [comment]
Maybe try with a portable version of Java? see for example here: https://github.com/jdemetra/rjdemetra/wiki/Installation-manual

**Comment by palatej** [comment]
There is a bug in rstudio with any java-based packages. Use either R-Studio 4.1.* or R-Studio R-studio 4.3.*

**Comment by DonPipo85** [comment]
Thanks for the helpful comments, I will do as recommended.
