### ISSUE TITLE
Avoid negative values

### ISSUE THREAD

**Issue by jo-fleck** [jdemetra/rjdemetra#127]
I am trying to seasonally adjust quarterly employment data for different industries in US counties (measured in number of workers). 

To my surprise, x13 sometimes returns negative values.

I assume it's because some of the data numbers are low (e.g. 50) or zero (but they are never negative of course).

I searched the documentation for an option to avoid negative seasonally adjusted values but could not find anything.

Is there any feature or setting that might help with this issue?

Thanks.

**Comment by AQLT** [comment]
There is no specific option for that. The negative values can usually be avoided using multiplicative decomposition. In your case, you have very small values that might prevent using multiplicative decomposition, you can try with pseudo-additive (see for example https://www.abs.gov.au/websitedbs/D3310114.nsf/home/Time+Series+Analysis:+The+Basics) using the `x11.mode` parameter.

**Comment by jo-fleck** [comment]
Many thanks for the instructions and the reference - very helpful!
