### ISSUE TITLE
Create spec from string in X13 format

### ISSUE THREAD

**Issue by edugca** [jdemetra/rjdemetra#130]
Hi,

How can I create a spec object in R from a string in X13 format such as the one in the example below:

series{
    start= 1996.1
    period = 4
    format = free
}
transform{ 
    function = auto
}
pickmdl{
   method = best
   identify = all
}
outlier{ 
    types = all
}
forecast {
   maxlead = 6
   maxback = 0
}
regression {
   aictest = (td easter)
}
estimate{ }
x11{
save = ( d10 d11 d12 d13 d16 d18)
savelog = q
}

**Comment by AQLT** [comment]
Hi,
You can't: `RJDemetra` is an R interface to the JDemetra+ software, which is different from the X-13ARIMA-SEATS Census Bureau binaries. Even though they implement the same method, some options are different and the way to create a spec is very different. If you want to read census bureau program specification files from R, you need to look in the [`seasonal`](https://github.com/christophsax/seasonal) package.
