### ISSUE TITLE
fcst.horizon in x13_spec does not have any effect

### ISSUE THREAD

**Issue by jonlachmann** [jdemetra/rjdemetra#143]
I just started using RJDemetra and am very impressed with most things so far. However, I tried to change the forecast horizon of the model in order to use the results for forecasting, but the ``fcst.horizon`` flag of ``x13_spec`` does not appear to have any effect.

Am I doing something wrong, or is there a bug here? I have created this minimal example to show what I mean, note how the last row will print 12 and not 36 as I expected.

```
library(RJDemetra)
myseries <- ipi_c_eu[, "FR"]
spec <- x13_spec(fcst.horizon = 36)
x13_model <- x13(myseries, spec = spec)
nrow(x13_model$final$forecasts)
```

**Comment by AQLT** [comment]
The parameter `fct.horizon` has no impact on the decomposition, you must use `x11.fcasts` parameter
``` r
library(RJDemetra)
myseries <- ipi_c_eu[, "FR"]
spec <- x13_spec(fcst.horizon = 46,
                 x11.fcasts = 36)
x13_model <- x13(myseries, spec = spec)
nrow(x13_model$regarima$forecast)
#> [1] 46
nrow(x13_model$final$forecasts)
#> [1] 36
```
