### ISSUE TITLE
Preliminary check in SA models

### ISSUE THREAD

**Issue by froehmar** [jdemetra/rjdemetra#39]
Hello,
I want to adjust a time series with x13. 
The code I enclose worked for other series, but I enclose a specific series where I got an error I cannot understand (the series can be adjusted in x12).
The series is the following:
x <- c(935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,917.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,935.00,935.00,935.00,935.00,1227.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
          935.00,935.00,935.00,878.80,794.85,964.77,385.00,903.56,923.62,923.37,924.33,924.10)

I use the following code for execution (I need the table .b1)
x <- ts(x,start=c(1999,1),freq=12)
mysa <- x13_spec_def(x,spec=c("RSA0"),transform.function = "None",automdl.enabled =FALSE,
                                arima.p=0,  arima.d=1,  arima.q=1, estimate.exclFirst = 0,
                                estimate.exclLast = 0,
                                arima.bp=0, arima.bd=1, arima.bq=1, outlier.usedefcv = FALSE,
                                outlier.enabled=TRUE, outlier.ao=TRUE, outlier.ls=FALSE,
                                outlier.tc=FALSE, outlier.so=FALSE, outlier.cv=15,
                                tradingdays.autoadjust = FALSE, tradingdays.option="TradingDays",
                                tradingdays.leapyear="LeapYear")
x13out <-  x13(x,mysa,userdefined = c("decomposition.b1"))

With this I get the following message:
Error in .jcall("ec/tstoolkit/jdr/sa/Processor", "Lec/tstoolkit/jdr/sa/X13Results;",  : 
  java.lang.NullPointerException

Could you please give me a hint whats wrong with my code?

kind regards,
Markus Fröhlich

**Comment by palatej** [comment]
By design, JDemetra+ will not process such a series (which is mostly constant). Applying seasonal adjustment is in that case a bad idea. However, we should return a more meaningful result.
It should also be noted that we can force estimation in the underlying java routine. Currently, that option is not available in R. To be added (but to use with caution).

**Comment by froehmar** [comment]
It was not intended to do seasonal adjustment for this series, but I use the routine to outlier adjust 10.000 series. However, also in this case it would be helpful to identify the outlying observations.

**Comment by AQLT** [comment]
If you just to outlier adjust your series you can use the `regarima()` function. With your example:
``` r
x <- c(935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,917.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,1227.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,878.80,794.85,964.77,385.00,903.56,923.62,923.37,924.33,924.10)

x <- ts(x,start=c(1999,1),freq=12)
library(RJDemetra)
regarima_spec <- regarima_spec_def_x13(spec=c("RG0"),transform.function = "None",automdl.enabled =FALSE,
                     arima.p=0, arima.d=1, arima.q=1, estimate.exclFirst = 0,
                     estimate.exclLast = 0,
                     arima.bp=0, arima.bd=1, arima.bq=1, outlier.usedefcv = FALSE,
                     outlier.enabled=TRUE, outlier.ao=TRUE, outlier.ls=FALSE,
                     outlier.tc=FALSE, outlier.so=FALSE, outlier.cv=15,
                     tradingdays.autoadjust = FALSE, tradingdays.option="TradingDays",
                     tradingdays.leapyear="LeapYear")
regarima_model <- regarima(x, regarima_spec)
regarima_model
#> y = regression model + arima (0, 1, 1, 0, 1, 1)
#> Log-transformation: no
#> Coefficients:
#>           Estimate Std. Error
#> Theta(1)   -0.8965      0.066
#> BTheta(1)  -0.5550      0.229
#> 
#>           Estimate Std. Error
#> Monday      29.837      19.34
#> Tuesday    -27.170      19.69
#> Wednesday    9.831      19.10
#> Thursday    30.755      19.39
#> Friday     -19.539      19.34
#> Saturday    10.047      19.34
#> Leap year   30.488      52.29
#> 
#> 
#> Residual standard error: 72.86 on 71 degrees of freedom
#> Log likelihood = -408.4, aic = 836.8 aicc = 840.5, bic(corrected for length) = 9.117
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by froehmar** [comment]
Thank you!

**Comment by AQLT** [comment]
I added a `preliminary.check` argument in the last pull request (#43). Note that all the _def functions are now deprecated: use `x13_spec` instead of `x13_spec_def`

``` r
library(RJDemetra)
x <- c(935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,917.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,1227.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,935.00,
       935.00,935.00,935.00,878.80,794.85,964.77,385.00,903.56,923.62,923.37,924.33,924.10)

x <- ts(x,start=c(1999,1),freq=12)
myspec1 <- x13_spec(spec=c("RSA0"), transform.function = "None",automdl.enabled =FALSE,
                     arima.p=0, arima.d=1, arima.q=1, estimate.exclFirst = 0,
                     estimate.exclLast = 0,
                     arima.bp=0, arima.bd=1, arima.bq=1, outlier.usedefcv = FALSE,
                     outlier.enabled=TRUE, outlier.ao=TRUE, outlier.ls=FALSE,
                     outlier.tc=FALSE, outlier.so=FALSE, outlier.cv=15,
                     tradingdays.autoadjust = FALSE, tradingdays.option="TradingDays",
                     tradingdays.leapyear="LeapYear")
x13out <- x13(x, myspec1, userdefined = c("decomposition.b1"))
#> Error in x13.SA_spec(x, myspec1, userdefined = c("decomposition.b1")): [input: Too many identical values]
myspec2 <- x13_spec(spec = myspec1, preliminary.check = FALSE)
x13out <- x13(x, myspec2, userdefined = c("decomposition.b1"))
```

<sup>Created on 2019-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
