### ISSUE TITLE
Error while installing the package rjdemetra

### ISSUE THREAD

**Issue by sakflex** [jdemetra/rjdemetra#40]
This is the message I get while installing (`devtools::install_github("jdemetra/rjdemetra", args = "--no-multiarch")`) the main package:

Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/.../RJDemetra_0.1.1.tar.gz’ had non-zero exit status

Does anyone have a clue what is the cause and how to solve it?

**Comment by AQLT** [comment]
Hi,
Which OS and which R version  are you using? You can now try to install the package from CRAN `install.package("RJDemetra")`

**Comment by sakflex** [comment]
Installing the package straight from CRAN worked perfectly. Thank you very much!

I still checked intsalling the package through devtools, still not working, although I reinstalled both Java and Rstudio making sure both were on a 64 bits version. My OS is Windows 10 and R version is 3.5.2
