### ISSUE TITLE
Outlier detection

### ISSUE THREAD

**Issue by NataliaSV** [jdemetra/rjdemetra#57]
Hi!
In JDemetra+, there is a section called Anomaly detection.
I would like to use the 'check last' and 'outlier detection' options for the data quality of many databases. Is there a function that can help me with that? I've already checked the R Documentation available [here](https://cran.r-project.org/web/packages/RJDemetra/RJDemetra.pdf) without success.

**Comment by AQLT** [comment]
Hi,
No there is no function in RJDemetra to directly use those option but you can easily compute the statistics. The methodology used is described here: https://jdemetradocumentation.github.io/JDemetra-documentation/pages/reference-manual/Statistical-methods.html.
Which information do you need in 'outlier detection' ? It seems to me that all the informations are exported by default with the regARIMA model.

**Comment by NataliaSV** [comment]
Hi! Sorry for the delay in my response.
What I have done so far is the following:

I want to use RJDemetra to check the presence of outliers in the new data. For example, for each time series in a database, I receive every month a new observation. I want to use R and JDemetra to check if this new observation is congruent with previous existent data (in JDemetra I would do that using the Check Last Batch). 

So, in RJDemetra I know how to adjust a model (a TRAMO model) and then made some forecasts.  Up to here, I have calculated the Absolute error column ( from the "Check Last Batch"), what I want to do now is to calculate the relative error. I have read the documentation you sent me, and some original TERROR papers, but I have not been able to replicate the Relative error column of the output with the results I obtained from JDemetra. The link you sent me says:

"The last observations (one, two or three, depending of the user’s choice) are compared with the forecasted values. If, for a given observation, the forecast error divided by a standard deviation of residuals is greater than the first threshold value and lower than the second threshold value..."

Once I got the residuals of my fitted model, I calculate the standard deviation. R also displays this statistic. However, the number to compare to a threshold I am obtaining from R and from JDemetra are totally different. Am I doing something wrong? 

 In addition, if I calculate the standard deviation of the residuals and divide the absolute error by it I do not get the same result as in JDemetra. 

I hope you can help me. I have read many papers and I agree that it is supposed to be very easy but  I do not understand why I am getting different results.

Thank you,
Natalia

**Comment by AQLT** [comment]
Hi,

Could you please provide a reproductible example with:

- one of your time series (you can for example export it with the function `dput()`).
- the code you use to compute the relative error
- the target in JDemetra+

Alain

**Comment by AQLT** [comment]
You can use the function below to compute what you want. There is an example with a simple data:

``` r
library(rJava)
library(RJDemetra)
jd_checklast<-function(s, last=1, method="TRfull", absoluteErrors=FALSE){
    jspec<-.jcall("ec/tstoolkit/modelling/arima/tramo/TramoSpecification", "Lec/tstoolkit/modelling/arima/tramo/TramoSpecification;", "fromString", method)
    jprocessor<-.jcall(jspec, "Lec/tstoolkit/modelling/arima/IPreprocessor;", "build")
    jcl<-.jnew("ec/tstoolkit/modelling/arima/CheckLast", jprocessor)
    .jcall(jcl, "V", "setBackCount", as.integer(last))
    if (.jcall(jcl, "Z", "check", RJDemetra:::ts_r2jd(s))){
        x<-numeric(length=last)
        for (i in 1:length(x)){
            if (absoluteErrors)
                x[i]=.jcall(jcl, "D", "getAbsoluteError", as.integer(i-1))
            else
                x[i]=.jcall(jcl, "D", "getRelativeError", as.integer(i-1))
        }
        x
    }
}
jd_checklast(ipi_c_eu[, "FR"], last = 3, absoluteErrors = FALSE)
#> [1] 2.2513555 1.3815750 0.4770303
jd_checklast(ipi_c_eu[, "FR"], last = 3, absoluteErrors = TRUE)
#> [1] 4.1997569 2.6793028 0.9766017
```

<sup>Created on 2020-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
