### ISSUE TITLE
Frequency of Time Series for filter selection

### ISSUE THREAD

**Issue by froehlich1** [jdemetra/rjdemetra#73]
Hi,

I tried to reproduce results from JDemetra+ in RJDemetra. I did this exercice on quarterly series. Everything is reproduceable but not the length of the automatic henderson filter length choice. If I apply:

testspec <- x13_spec(spec = "RSA3", transform.function = "Log")
x13(tsQuarterly, testspec) (tsQuarterly is a quarterly ts object)

then RJDemetra selects a 13 term henderson filter (whereas JDemetra+ selects a 5-term henderson filter)
This is true for almoust all quarterly series I tested.
So do I have to deliver the frequency somehow to the function x13_spec ( I assumed that the program should check the frequency from the time-series object automatically)

best regards,
markus.

**Comment by palatej** [comment]
Hi,

Thanks for your remark.
There is indeed a bug in the current implementation: the length of the Henderson filter is not correctly selected; that is especially annoying for quarterly series. See #74 for the correction. 
The corrected package will be deployed with the next release of JD+ (probably in April).

Jean
