### ISSUE TITLE
RegARIMA models on annual time series

### ISSUE THREAD

**Issue by monicaIdescat** [jdemetra/rjdemetra#77]
I am using the JDemetra + GUI to forecast annual time series with TRAMO specifications. I have noticed that for some series the Ljung-Box and Box-Pierce tests on seasonality are shown (Pre-processing|Residuals|Statistics output) and for others not. 

When I try to forecast these last series with RJDemetra, the _**regarima_tramoseats**_ command fails with an error message,throwed by the sentence _rownames(tests) <- c("mean", "skewness", "kurtosis", "ljung box", "ljung box (residuals at seasonal lags)", "ljung box (squared residuals)")_ of the function _**regarima_rslts**_:

Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

Maybe I'm not using JDemetra + in the most appropriate way.

Thanks in advance. Here is an example:

ts.works<-ts(c(31330.81,33295.32,33537.83,34264.78,35988.31,36292.1,37924.94,39484.94,39574.35,34792.39,36636.8,36830.45,35142.46,35638.85,36846.38,39350.22,40640.44,42797.83,43603.59,44333.21), start=2000,frequency=1)

RJDemetra::regarima_tramoseats(ts.works,spec="TRfull")

ts.fails<-ts(c(10995.847,12493.258,13656.16,14787.893,16415.115,18782.743,21372.625,22774.239,21357.988,16319.45,13924.322,10760.941,9171.683,8976.568,9379.19,10132.072,10766.467,11443.373,12207.556),start=2000,frequency=1)

RJDemetra::regarima_tramoseats(ts.fails,spec="TRfull")

![imatge](https://user-images.githubusercontent.com/64467190/80474632-fa1b5500-8947-11ea-8304-85be0b091680.png)
![imatge](https://user-images.githubusercontent.com/64467190/80474734-1dde9b00-8948-11ea-98b2-a085bb844ecf.png)

**Comment by palatej** [comment]
Hello,

Thank you for your remark.
Seasonal tests should not be computed on yearly series. I will correct the problem in the next release (2.2.3) and adapt the R package accordingly.
