### ISSUE TITLE
x11.seasonalma does not work(?)

### ISSUE THREAD

**Issue by Beethoven090** [jdemetra/rjdemetra#78]
Hello,

unfortunately, I cannot figure out how to adjust the seasonal filter in X-13ARIMA-SEATS. No matter which vector I use in the "x11.seasonalma" command, it does not even marginally change the outcome of the sa process. 

This is also confirmed by the following. So, when I instruct `mysamodel <- x13(myseries, x13_spec(x11.seasonalma="S3X9"))`, and when I then look into the seasonal filter specification used in `mysamodel`, it shows that the model still used the default "Msr": `mysamodel$decomposition$specification$x11.seasonalma`
`[1] "Msr"`

So, how can I adjust `x11.seasonalma`? Is there a pre-specifiation which I need to adjust first (e.g. for `x11.trendma` to work, one must specify `x11.trendAuto=FALSE` first)? Or is there another solution?

Thank you for your help!

**Comment by AQLT** [comment]
Hi,
Indeed there was an error in the code that checks if the specification is correct. This is fixed in the last pull-request (#79). 
Thank you for reporting.
