### ISSUE TITLE
UserDefined on tradingdays.option

### ISSUE THREAD

**Issue by sakflex** [jdemetra/rjdemetra#80]
Hi all!

I have been using the software Jdemetra for a while. Now I have started trying to implement some of my models and forecasts in Rjdemetra. My question is regarding the user-defined calendar variable and its impossibility to be used in RJdemetra, if I try to use user-defined calendar variable (as I did in Jdemetra app) it appears the following message:

"Warning message:
With tradingdays.option = "UserDefined", the parameters tradingdays.leapyear and tradingdays.stocktd are ignored."

My question is if this issue is gonna be solved in the next upgrade of the package or wether I can fix it manually copying the code from the package and modify on my own.

Thanks!

**Comment by AQLT** [comment]
Hi,
Indeed it might not be clear: for the moment RJDemetra doesn't support user-defined calendar (as it is possible in JDemetra+). This option allows to use user-defined calendar regressors, as in JDemetra+ when you use the option "UserDefined" (see https://sylwiagrudkowska.github.io/JDemetra-documentation/pages/case-studies/detailedsa-calendarvariables.html). 
To use your user-defined calendar you have to export the associated regressors and add then with the options `usrdef.varEnabled = TRUE`, `usrdef.var` and `usrdef.varType` as in this unrealistic example:
``` r
library(RJDemetra)
myseries <- ipi_c_eu[, "FR"]
var1 <- ts(rnorm(length(myseries))*10, start = start(myseries), frequency = 12)
var2 <- ts(rnorm(length(myseries))*100, start = start(myseries), frequency = 12)
var <- ts.union(var1, var2)
myspec1 <- x13_spec(spec = "RSA5c", tradingdays.option = "UserDefined",
                    tradingdays.test = "None",
                    usrdef.varEnabled = TRUE,
                    usrdef.var = var,
                    usrdef.varType = c("Calendar", "Calendar"))
#> Warning: With tradingdays.option = "UserDefined", the parameters tradingdays.autoadjust, tradingdays.leapyear and tradingdays.stocktd are ignored.
myreg1 <- x13(myseries, myspec1)
myreg1$regarima
#> y = regression model + arima (3, 1, 1, 0, 1, 1)
#> Log-transformation: yes
#> Coefficients:
#>           Estimate Std. Error
#> Phi(1)     0.31926      0.370
#> Phi(2)     0.05644      0.368
#> Phi(3)    -0.42715      0.265
#> Theta(1)  -0.68590      0.356
#> BTheta(1) -0.73413      0.040
#> 
#>                Estimate Std. Error
#> var1         -1.261e-04      0.000
#> var2         -1.174e-05      0.000
#> Easter [8]   -2.487e-02      0.006
#> LS (11-2008) -9.277e-02      0.017
#> AO (5-2011)   8.732e-02      0.021
#> LS (1-2009)  -7.537e-02      0.017
#> 
#> 
#> Residual standard error: 0.02688 on 335 degrees of freedom
#> Log likelihood = 757.1, aic =  1715 aicc =  1716, bic(corrected for length) = -7.047
```

It will be easier to include user-defined calendar compatibility with JDemetra+ 3.0 but for the moment it is not possible (RJDemetra doesn't contains all the java libraries of JDemetra+). I cannot tell when it will be fixed.
