### ISSUE TITLE
Importing a nowcasting model

### ISSUE THREAD

**Issue by krlndrd** [jdemetra/rjdemetra#82]
I've tried to import a dynamic factor model within a workspace with the package, but it does not work. Does the package support this kind of specifications? Or is it only for seasonal adjustment? 

Whenever I try to access the model with get_model(wk), it gives me this error:
"Error in tramoseatsJavaResults(jrslt = jrslt, spec = spec, userdefined = userdefined, : [preprocessing: failed]
Error while importing a model: NULL object will be returned"

**Comment by palatej** [comment]
Hello,

The R package only supports seasonal adjustment. We plan to extend it to nowcasting and other time series methods in the next years (not before 2023).

Jean
