### ISSUE TITLE
Problem with  x13(myseries, spec = myspec1)

### ISSUE THREAD

**Issue by ChristianeHofer** [jdemetra/rjdemetra#99]
The example:
library(RJDemetra)
myseries <- ipi_c_eu[, "FR"]
myspec1 <- x13_spec(spec = "X11",x11.mode="Additive")
my_model <- x13(myseries, spec = myspec1)

is running with Version 0.1.6 but not with Version 0.1.9: 
I receive the message: 
Fehler in specX11_r2jd(spec, jdspec, freq = frequency(series)) : 
  Objekt 'jdspec' nicht gefunden
That means error in specX11_r2jd(spec, jdspec, freq = frequency(series)) : Object 'jdspec' not found
What should I do? 
Thanks Christiane

**Comment by AQLT** [comment]
Try to restart R, create a new RStudio projet or restart your session with the function `.rs.restartR()`. I've test it on two different OS and I don't have this issue with RJDemetra 0.1.6. Note that it might not work if you a rjd3 package loaded (that's why I recommend to restart R):
``` r
library(RJDemetra)
myseries <- ipi_c_eu[, "FR"]
myspec1 <- x13_spec(spec = "X11",x11.mode="Additive")
my_model <- x13(myseries, spec = myspec1) #works

library(RJDemetra3)
my_model <- x13(myseries, spec = myspec1)
#> Error in type$value(name = paste(prefix, code, sep = "_"))$number(): tentative d'appliquer un objet qui n'est pas une fonction
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ChristianeHofer** [comment]
Thanks,  this was the solution

**Comment by ChristianeHofer** [comment]
Version 0.1.6 is running well but not version 0.1.9

**Comment by ChristianeHofer** [comment]
I think the problem might be, that RJDemetra needs grDevices (Version 4.0.2) this Package has a Method X11

**Comment by AQLT** [comment]
This time it should be good: a small typo was introduced in the code in PR #97 that only affects the code with the X11 specification (yesterday I only test the code in RJDemetra 0.1.6...). It should be fixed with PR #100.

**Comment by ChristianeHofer** [comment]
Thanks now with version 0.2.0 it works.

**Comment by ChristianeHofer** [comment]
The package on Cran is 0.1.9? When are you going to update it? 

Thanks Christiane

**Comment by AQLT** [comment]
Yes on CRAN is still 0.1.9. I just came back from holidays ✈️, if there is no problem with CRAN, v2.0.0 should be on CRAN by the end of the next week.

**Comment by AQLT** [comment]
It is now on CRAN!

**Comment by ChristianeHofer** [comment]
Thanks
